apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teams-notifier.fullname" . }}
  labels:
    {{- include "teams-notifier.labels" . | nindent 4 }}
type: Opaque
stringData:
  TEAMS_WEBHOOK_URL: {{ required "teamsWebhookUrl is required" .Values.teamsWebhookUrl | quote }}
  {{- if .Values.webhookSecret }}
  TEAMS_WEBHOOK_SECRET: {{ .Values.webhookSecret | quote }}
  {{- end }}
